/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomFieldFilter } from './custom-field-filter.model';


export interface AdvancedSearch { 
    q?: string;
    propertyTypeId?: string;
    areaId?: string;
    includeArchived?: boolean;
    page?: number;
    pageSize?: AdvancedSearch.PageSizeEnum;
    customFilters?: Array<CustomFieldFilter>;
}
export namespace AdvancedSearch {
    export const PageSizeEnum = {
        NUMBER_10: 10,
        NUMBER_25: 25,
        NUMBER_50: 50,
        NUMBER_100: 100,
    } as const;
    export type PageSizeEnum = typeof PageSizeEnum[keyof typeof PageSizeEnum];
}


