/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ArchivePropertyRequest { 
    version: number;
    /**
     * Optional Arabic note explaining why the property is being archived. Shown on the detail while archived and in the audit row\'s detail; cleared on restore. 
     */
    note?: string;
}

