/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExtractState } from './extract-state.model';


export interface Attachment { 
    id: string;
    propertyId: string;
    description: string;
    originalFilename: string;
    /**
     * Determined from content
     */
    contentType: string;
    byteSize: number;
    /**
     * True means the extracted text is encrypted and never searched. May be raised, never lowered. 
     */
    isSensitive: boolean;
    extractState: ExtractState;
    /**
     * A reason code. Never any part of the document\'s content.
     */
    extractError?: string | null;
    /**
     * True for `pdf` and images. False means the client offers a download instead of a viewer (FR-013c). 
     */
    canViewInline: boolean;
    createdAt: string;
    createdBy: string;
    updatedAt?: string;
    updatedBy?: string;
}
export namespace Attachment {
}


