/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AttachmentText { 
    attachmentId: string;
    /**
     * Absent when extraction found nothing or has not run. For a sensitive attachment this is the decrypted text, returned only after the role check. 
     */
    body?: string | null;
    /**
     * True when the document produced more text than the configured cap, so a phrase past the cut will not be found (FR-021). 
     */
    truncated: boolean;
    isCorrected: boolean;
    correctedBy?: string | null;
    correctedAt?: string | null;
    extractedAt?: string | null;
}

