/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role.model';
import { AuditAction } from './audit-action.model';


/**
 * A record is never rewritten. The snapshot fields show accounts as they were named when the action happened, even if renamed since. Never contains a password, a decrypted value, a key, or a wrapped key (Constitution VII). 
 */
export interface AuditRecord { 
    id: number;
    occurredAt: string;
    action: AuditAction;
    /**
     * Null when the actor was never authenticated, such as a failed sign-in with an unknown username.
     */
    actorId?: string | null;
    actorUsername: string;
    actorRole?: Role | null;
    /**
     * The kind of business record this row concerns, when any.
     */
    entityType?: AuditRecord.EntityTypeEnum | null;
    /**
     * The identifier of that record (a reference code for a property).
     */
    entityId?: string | null;
    targetId?: string | null;
    targetUsername?: string | null;
    sourceIp: string;
    /**
     * Field names and identifiers only.
     */
    detail?: { [key: string]: any; } | null;
}
export namespace AuditRecord {
    export const EntityTypeEnum = {
        Property: 'property',
        PropertyType: 'property_type',
        Area: 'area',
        CustomField: 'custom_field',
    } as const;
    export type EntityTypeEnum = typeof EntityTypeEnum[keyof typeof EntityTypeEnum];
}


