/**
 * Property Management System — Authentication and Accounts
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role.model';
import { AuditAction } from './audit-action.model';


/**
 * A record is never rewritten. The snapshot fields show accounts as they were named when the action happened, even if renamed since. Never contains a password or any decrypted value (FR-025). 
 */
export interface AuditRecord { 
    id: number;
    occurredAt: string;
    action: AuditAction;
    /**
     * Null when the actor was never authenticated, such as a failed sign-in with an unknown username.
     */
    actorId?: string | null;
    actorUsername: string;
    actorRole?: Role | null;
    targetId?: string | null;
    targetUsername?: string | null;
    sourceIp: string;
    /**
     * Field names and identifiers only.
     */
    detail?: { [key: string]: any; } | null;
}
export namespace AuditRecord {
}


