/**
 * Property Management System — Authentication and Accounts
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AuditAction = {
    SignInSucceeded: 'sign_in_succeeded',
    SignInFailed: 'sign_in_failed',
    SignOut: 'sign_out',
    PasswordChanged: 'password_changed',
    PasswordReset: 'password_reset',
    AccountCreated: 'account_created',
    AccountRoleChanged: 'account_role_changed',
    AccountActivated: 'account_activated',
    AccountDeactivated: 'account_deactivated',
    SessionsInvalidated: 'sessions_invalidated',
    AdminRecoveryUsed: 'admin_recovery_used',
} as const;
export type AuditAction = typeof AuditAction[keyof typeof AuditAction];

