/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChangePropertyCodeRequest { 
    /**
     * Unique across the register, active and archived alike, compared after trimming, case folding, and Arabic normalisation. Never reused. 
     */
    code: string;
    version: number;
}

