/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role.model';


export interface CreateUserRequest { 
    username: string;
    displayName: string;
    role: Role;
    initialPassword: string;
}
export namespace CreateUserRequest {
}


