/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role.model';


/**
 * The caller as they stand on this request. `mustChangePassword` true means the client must send the user to the password-change screen and no other. 
 */
export interface CurrentUser { 
    id: string;
    username: string;
    displayName: string;
    role: Role;
    mustChangePassword: boolean;
}
export namespace CurrentUser {
}


