/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * `autocomplete` is free text stored and validated exactly like `text`; the difference is advisory only — the client offers, via /properties/field-suggestions, values already entered for the same field on other properties. Suggestions never constrain what may be saved. An `autocomplete` field can never be sensitive. 
 */
export const CustomFieldType = {
    Text: 'text',
    Autocomplete: 'autocomplete',
    Dropdown: 'dropdown',
    Multiselect: 'multiselect',
    Checkbox: 'checkbox',
} as const;
export type CustomFieldType = typeof CustomFieldType[keyof typeof CustomFieldType];

