/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomFieldUpdate { 
    label: string;
    addChoices?: Array<string>;
    removeChoiceIds?: Array<string>;
}

