/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomFieldChoice } from './custom-field-choice.model';
import { CustomFieldType } from './custom-field-type.model';


export interface CustomField { 
    id: string;
    label: string;
    fieldType: CustomFieldType;
    /**
     * True only for a `text` field. Its values are encrypted at rest and it cannot be searched, sorted, or filtered (Constitution VII). 
     */
    isSensitive: boolean;
    choices: Array<CustomFieldChoice>;
    /**
     * Number of properties (active or archived) holding a value for this field. Sensitivity and type are fixed once this is non-zero (FR-027s5, FR-027g). Always zero for fields created in this response. 
     */
    valuesCount?: number;
}
export namespace CustomField {
}


