/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Exactly one of the value members is present, matching the field\'s type. A sensitive field\'s value arrives here decrypted, and only on the property detail — never in a list or a search result. 
 */
export interface CustomFieldValue { 
    fieldId: string;
    text?: string | null;
    checked?: boolean | null;
    choiceId?: string | null;
    choiceIds?: Array<string>;
}

