/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomFieldType } from './custom-field-type.model';


export interface CustomFieldCreate { 
    label: string;
    fieldType: CustomFieldType;
    isSensitive?: boolean;
    choices?: Array<string>;
}
export namespace CustomFieldCreate {
}


