/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchOperator } from './search-operator.model';


export interface CustomFieldFilter { 
    fieldId: string;
    operator: SearchOperator;
    text?: string | null;
    choiceId?: string | null;
    choiceIds?: Array<string>;
}
export namespace CustomFieldFilter {
}


