/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const CustomFieldType = {
    Text: 'text',
    Dropdown: 'dropdown',
    Multiselect: 'multiselect',
    Checkbox: 'checkbox',
} as const;
export type CustomFieldType = typeof CustomFieldType[keyof typeof CustomFieldType];

