/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentSearchHit } from './document-search-hit.model';


export interface DocumentSearchPage { 
    items: Array<DocumentSearchHit>;
    page: number;
    pageSize: number;
    totalItems: number;
    /**
     * Always true. Present so the client can state in Arabic that sensitive documents are not searched, rather than silently returning fewer results (FR-022b). 
     */
    sensitiveExcluded: boolean;
}

