/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentSearchHit { 
    propertyId: string;
    propertyCode: string;
    propertyName: string;
    attachmentId: string;
    attachmentDescription: string;
}

