/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * `empty` and `not_eligible` are normal outcomes, not errors. `not_eligible` also covers a document whose family needs a tool that is not installed (research.md D-012), which the client reports in Arabic rather than as a failure. 
 */
export const ExtractState = {
    Pending: 'pending',
    Done: 'done',
    Empty: 'empty',
    NotEligible: 'not_eligible',
    TooLarge: 'too_large',
    Failed: 'failed',
} as const;
export type ExtractState = typeof ExtractState[keyof typeof ExtractState];

