/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type-ahead values for one filter, most used first. Never derived from an encrypted value; a sensitive field is refused before the query (Constitution VII). 
 */
export interface FieldSuggestions { 
    suggestions: Array<string>;
}

