/**
 * Property Management System — Authentication and Accounts
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetHealth200Response { 
    status: GetHealth200Response.StatusEnum;
}
export namespace GetHealth200Response {
    export const StatusEnum = {
        Ok: 'ok',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


