/**
 * Property Management System — Authentication and Accounts
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditRecord } from './audit-record.model';


export interface ListAuditRecords200Response { 
    items: Array<AuditRecord>;
    page: number;
    pageSize: number;
    totalItems: number;
}

