/**
 * Property Management System — Authentication and Accounts
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user.model';


export interface ListUsers200Response { 
    items: Array<User>;
    page: number;
    pageSize: number;
    totalItems: number;
}

