/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The single error shape used by every operation in this document (Constitution III). `message` is Arabic and states what the user should do next. It never carries internal failure detail, a key, a wrapped key, or a decrypted value (Constitution VII). 
 */
export interface ModelError { 
    code: ModelError.CodeEnum;
    /**
     * Arabic, user-facing.
     */
    message: string;
    /**
     * Field-level Arabic messages, keyed by field name, for form errors.
     */
    fields?: { [key: string]: string; } | null;
    /**
     * Seconds remaining before another attempt is accepted (sign-in throttling).
     */
    retryAfterSeconds?: number | null;
}
export namespace ModelError {
    export const CodeEnum = {
        InvalidRequest: 'invalid_request',
        InvalidCredentials: 'invalid_credentials',
        TooSoon: 'too_soon',
        NotAuthenticated: 'not_authenticated',
        Forbidden: 'forbidden',
        NotFound: 'not_found',
        Conflict: 'conflict',
        InUse: 'in_use',
        VersionConflict: 'version_conflict',
        Archived: 'archived',
        PasswordChangeRequired: 'password_change_required',
        InternalError: 'internal_error',
    } as const;
    export type CodeEnum = typeof CodeEnum[keyof typeof CodeEnum];
}


