/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomFieldValue } from './custom-field-value.model';


export interface PropertyUpdate { 
    /**
     * Descriptive, not identifying. Two properties may share a name. 
     */
    name: string;
    propertyTypeId: string;
    areaId: string;
    version: number;
    customValues?: Array<CustomFieldValue>;
}

