/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomFieldValue } from './custom-field-value.model';


export interface PropertyCreate { 
    /**
     * Descriptive, not identifying. Two properties may share a name. 
     */
    name: string;
    /**
     * Must name a configured type; a free-typed value is impossible.
     */
    propertyTypeId: string;
    areaId: string;
    /**
     * Administrator only. A manager supplying it is refused with 403. Omitted, the server generates the next code. 
     */
    code?: string;
    customValues?: Array<CustomFieldValue>;
}

