/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Lookup } from './lookup.model';
import { PropertySummaryMatchedAttachmentsInner } from './property-summary-matched-attachments-inner.model';


/**
 * One row of the list. Custom values are not included here.
 */
export interface PropertySummary { 
    id: string;
    /**
     * Unique across the register, active and archived alike, compared after trimming, case folding, and Arabic normalisation. Never reused. 
     */
    code: string;
    /**
     * Descriptive, not identifying. Two properties may share a name. 
     */
    name: string;
    propertyType: Lookup;
    area: Lookup;
    isArchived: boolean;
    /**
     * Present only when `documentText` was part of the search. Names the attachments whose extracted text matched, so a hit says *why* it matched rather than only *that* it did (FR-026). 
     */
    matchedAttachments?: Array<PropertySummaryMatchedAttachmentsInner>;
}

