/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Lookup } from './lookup.model';


/**
 * One row of the list. Custom values are not included here.
 */
export interface PropertySummary { 
    id: string;
    /**
     * Unique across the register, active and archived alike, compared after trimming, case folding, and Arabic normalisation. Never reused. 
     */
    code: string;
    /**
     * Descriptive, not identifying. Two properties may share a name. 
     */
    name: string;
    propertyType: Lookup;
    area: Lookup;
    isArchived: boolean;
}

