/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomFieldValue } from './custom-field-value.model';
import { Lookup } from './lookup.model';


export interface PropertyDetail { 
    id: string;
    /**
     * Unique across the register, active and archived alike, compared after trimming, case folding, and Arabic normalisation. Never reused. 
     */
    code: string;
    /**
     * Descriptive, not identifying. Two properties may share a name. 
     */
    name: string;
    propertyType: Lookup;
    area: Lookup;
    isArchived: boolean;
    version: number;
    createdAt: string;
    createdBy: string;
    updatedAt: string;
    updatedBy: string;
    archivedAt?: string;
    archivedBy?: string;
    customValues: Array<CustomFieldValue>;
}

