/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PropertySummary } from './property-summary.model';


export interface PropertyPage { 
    items: Array<PropertySummary>;
    page: number;
    pageSize: number;
    totalItems: number;
}

