/**
 * Property Management System — Authentication and Accounts
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Exactly two roles exist (FR-002).
 */
export const Role = {
    Admin: 'admin',
    Manager: 'manager',
} as const;
export type Role = typeof Role[keyof typeof Role];

