/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * `contains` suits text; `equals` a dropdown; `includesAll` a multiselect; `isTrue`/`isFalse` a checkbox. The server checks the pairing and refuses a mismatch with 400. 
 */
export const SearchOperator = {
    Contains: 'contains',
    Equals: 'equals',
    IncludesAll: 'includesAll',
    IsTrue: 'isTrue',
    IsFalse: 'isFalse',
} as const;
export type SearchOperator = typeof SearchOperator[keyof typeof SearchOperator];

