/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SearchDocumentsRequest { 
    /**
     * Matched after the same Arabic normalisation as property names.
     */
    q: string;
    includeArchived?: boolean;
    page?: number;
    pageSize?: SearchDocumentsRequest.PageSizeEnum;
}
export namespace SearchDocumentsRequest {
    export const PageSizeEnum = {
        NUMBER_10: 10,
        NUMBER_25: 25,
        NUMBER_50: 50,
        NUMBER_100: 100,
    } as const;
    export type PageSizeEnum = typeof PageSizeEnum[keyof typeof PageSizeEnum];
}


