/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SignIn429Response { 
    code: SignIn429Response.CodeEnum;
    /**
     * Arabic, user-facing.
     */
    message: string;
    /**
     * Field-level Arabic messages, keyed by field name, for form errors.
     */
    fields?: { [key: string]: string; };
    /**
     * Seconds remaining before another attempt is accepted.
     */
    retryAfterSeconds: number;
}
export namespace SignIn429Response {
    export const CodeEnum = {
        InvalidRequest: 'invalid_request',
        InvalidCredentials: 'invalid_credentials',
        TooSoon: 'too_soon',
        NotAuthenticated: 'not_authenticated',
        Forbidden: 'forbidden',
        NotFound: 'not_found',
        Conflict: 'conflict',
        InUse: 'in_use',
        VersionConflict: 'version_conflict',
        Archived: 'archived',
        PasswordChangeRequired: 'password_change_required',
        TooLarge: 'too_large',
        UnsupportedType: 'unsupported_type',
        IntegrityFailed: 'integrity_failed',
        KeyUnavailable: 'key_unavailable',
        InternalError: 'internal_error',
    } as const;
    export type CodeEnum = typeof CodeEnum[keyof typeof CodeEnum];
}


