/**
 * Property Management System — Authentication and Accounts
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SignInRequest { 
    username: string;
    password: string;
}

