/**
 * Property Management System
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role.model';


export interface UpdateUserRequest { 
    displayName?: string;
    role?: Role;
    isActive?: boolean;
}
export namespace UpdateUserRequest {
}


